vmware-tanzu/vm-operator-api

api/v1alpha1/virtualmachineservice_types.go
api/v1alpha1/virtualmachinesetresourcepolicy_types.go

This seems to have been a typo in the annotations on the APIs resulting in the wrong signatures being generated in the generated client.

VirtualMachineService and VirtualMachineResourcePolicy can be namespaced

---

api/v1alpha1/virtualmachine_types.go

OvfEnv is a standard way to transport key/value vm customization data from the infrastructure to the VM, as well as exposing them to guest os/apps within the VM. Possible key/value properties that are userConfigurable would be already defined in the .ovf image as defined in the OVF Spec 2.1.1 Section 11 https://www.dmtf.org/sites/default/files/standards/documents/DSP0243_2.1.1.pdf 
This MR makes it possible to supply key/value fields to set the userConfigurable property fields on a .ovf during the VirtualMachine create time. The VirtualMachine spec already has a VmMetadata field which already supports a "ExtraConfig" transport, and this change adds another possible transport which is "OvfEnv".

Introduce OvfEnv VmMetadataTransport

---

api/v1alpha1/virtualmachine_types.go

VM operator now supportes VDS type networks, along with NSX-T type
networks. This change updates API type comments to indicate that.

Modify API type comments to indicate VDS networks are supported

---

api/v1alpha1/virtualmachineimage_types.go

InvalidGuestOSType is used to indicate that the GuestOS Type in VirtualMachineImageOSInfo is Invalid
and helps with validation during  VirtualMachineImage creation

Add SupportedOS boolean flag to the VirtualMachineImage status 

---

api/v1alpha1/virtualmachine_types.go

This adds PeriodSeconds to probe configuration, which indicates how often to perform the probe.
It also adds VirtualMachineReady condition type in virtualmachine status.

Update VM Probe configuration

---

api/v1alpha1/virtualmachine_types.go

We use API version v1beta1, which does not support defaulting.

Remove default value for TimeoutSeconds and PeriodSeconds.

---

api/v1alpha1/virtualmachineimage_types.go

This change adds two additional columns for `kubectl get virtualmachineimages`: Format and Source.
|Colums|Source|Description|
|-------|--------|-----------|
|`Format`|`.spec.type`|Describes template's type: ovf or vmtx|
|`Source`|`.spec.imageSourceType`|Points to content distribution platform - Content Library|
Example output:
```
kubectl get virtualmachineimages
NAME             VERSION    OSTYPE   FORMAT       SOURCE
photon-1568934    1.16      photon    ovf     Content Library
ubuntu-1778966    1.12      ubuntu    vmtx    Content Library
```

Improve VM Image column UX

---

api/v1alpha1/virtualmachineservice_types.go

1. Being able to statically assign IP addresses to LoadBalancer type VirtualMachineService is a very common ask from users;
2. Adding this field enables this functionality in the API implementation/Providers

Add loadBalancerIP field in VirtualMachineService

---

api/v1alpha1/virtualmachineservice_types.go

1. Other types, eg: LoadBalancer is also supported besides Client IP

Clean up comment

---

api/v1alpha1/virtualmachine_types.go

Introduce a InstanceUUID field to the VirtualMachine Status which reflect the vSphere Instance UUID.

Introduce InstanceUUID for VirtualMachine

---

api/v1alpha1/virtualmachineimage_types.go

Since VM operator only supports one type of Source - 'Content library'
for MVP, we can get rid of the SOURCE column in the default output.
This can be reintroduced later when needed.

Remove 'Source' column from "kubectl get virtualmachineimages"

---

api/v1alpha1/virtualmachineservice_types.go

1. This PR adds one more field `LoadBalancerSourceRanges` to the VirtualMachineService spec.
When supported by the underlying load balancer provider, ingress
traffic will be restricted to the specified list of Client IPs

Add LoadBalancerSourceRanges to VirtualMachineService spec

---

api/v1alpha1/virtualmachine_types.go

We should be able to Patch specific field(s) in the Status on a new VM
object but without this, Patch will fail due to missing required fields.
Pair with "// +optional" to match k8s API conventions [1]
[1] - https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required

Add omitempty to VirtualMachine Status fields

---

api/v1alpha1/virtualmachine_types.go

This patch provides the ability for clients to specify a
VirtualNetworkInterface (VIF) for a VM without specifying a
specific network by making NetworkName an optional parameter.
The network interface provider will then connect this VIF to
the default network for the namespace.
Testing Done:
- make all

Make NetworkName an optional parameter

---

api/v1alpha1/condition_consts.go

There are many developer workflows where do not provide any user feedback. This
change defines a Condition and a few reasons to address some of those
workflows.
The following Condition is defined:
- VirtualMachinePreReqReady:
A condition that represents that all the Prerequisites of a `VirtualMachine` are
ready. For now, we only check for the availability of `VirtualMachineClass` and
the that the class is associated with the VirtualMachine's namespace. In future,
this Condition can be used to check for other components as well
(e.g. `VirtualMachineImage`, `StorageClass` etc).
A few reasons are also defined:
- VirtualMachineClassBindingNotFound
If the VirtualMachine's namespace does not have access to the specified
`VirtualMachineClass`.
- VirtualMachineClassNotFound
If the specified …

Add Condition and Reasons for VirtualMachineClassBindings and VirtualMachineClasses

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha1/virtualmachineclass_types.go
api/v1alpha1/virtualmachineclassbinding_types.go
api/v1alpha1/virtualmachineimage_types.go
api/v1alpha1/virtualmachineservice_types.go

- Adding powerState on default and class, image on -o wide for virtualmachine
- Adding serviceType to virtualmachineservice
- Adding cpu & memory to virtualmachineclass
- Adding Age columns to crds with additional columns since they are omitted
from default when columns are mentioned explicitly for a crd.
Testing Done: 
```
root@4212e95af1461a21e76bcd525ad63941 [ ~ ]# kubectl get vm -A
NAMESPACE    NAME                          POWERSTATE   AGE
test-ns   jenkins-workload-1611253951   poweredOn    25h
root@4212e95af1461a21e76bcd525ad63941 [ ~ ]# kubectl get vm -o wide -A
NAMESPACE    NAME                          POWERSTATE   CLASS                IMAGE                       AGE
test-ns   jenkins-workload-1611253951   poweredOn    best-effort-xsmall   bitnami-jenkins-2.222.3-1   25h …
```

Add some useful columns to 'kubectl get'

---

api/v1alpha1/condition_consts.go

In order to provide better feedback to users when a VirtualMachineImage
specified in the VirtualMachine yaml is not available on the API server, or, if
the  developer's namespace does not have access to those images, this change
introduces Reasons that can be set on the conditions as part of the
VirtualMachine's Status.
Following Reasons are defined:
- ContentSourceBindingNotFoundReason
If the developer's namespace does not have access to use the specified
VirtualMachineImage.
- VirtualMachineImageNotFoundReason
If the specified VirtualMachineImage is not found.
These reasons are set on the VirtualMachinePreReqReady condition.

Add Condition and Reasons for ContentSourceBindings and VM Images

---

api/v1alpha1/virtualmachine_types.go

The power state of the VirtualMachine from the spec should match exactly as the
power states defined in the vim 25 API descriptions. The only allowed values are
"powredOn" and "poweredOff".
Similarly, the supported values for VM metadata transport are OvfEnv and
ExtraConfig, but we do not enforce them.
This change enforces these values by leveraging the kubebuilder validation
markers.

Enforce enum restrictions on VM power state and metadata transport 

---

api/v1alpha1/virtualmachine_types.go

Update comment on extraConfig transport stating only guestinfo* prefixed keys to be allowed

Update comment on extraConfig transport stating only guestinfo* prefixed keys to be allowed

---

api/v1alpha1/virtualmachine_types.go

Show vmIP or the "primary" IP address in the
`kubectl get vm -o wide` output.
Testing Done:
```
root@420cddeddb9f4f4df6bee259ad535225 [ ~ ]# kubectl get vm centos-vm-1 -n my-test-namespace -o wide
NAME          POWERSTATE   CLASS                IMAGE                                         PRIMARY-IP          AGE
centos-vm-1   poweredOn    best-effort-medium   centos-stream-8-vmservice-v1alpha1.20210222   192.168.128.5      6d15h
```

Add VM Primary IpAddress column to `kubectl get vm -o wide`

---

api/v1alpha1/virtualmachineclass_types.go

This patch adds GPU and Direct path IO device related information to the
kubectl get vmclass command in `-o wide` mode
If a VMClass does not have VGPU/Passthrough devices added, then the field will show up
as empty in the get output
Testing Completed:
```
root@42255e5e354ccbd32859ca7470f8897f [ ~ ]# kubectl get virtualmachineclasses.vmoperator.vmware.com vmclass-vgpu-mockup-vmiop -o wide
NAME                        CPU   MEMORY   AGE   VGPUDEVICES                        PASSTHROUGHDEVICES
vmclass-vgpu-mockup-vmiop   2     2Gi      32m   [{"profileName":"mockup-vmiop"}]
root@42255e5e354ccbd32859ca7470f8897f [ ~ ]# kubectl get virtualmachineclasses.vmoperator.vmware.com vmclass-vgpu-mockup-vmiopNAME                        CPU   MEMORY   AGE
vmclass-vgpu-mockup-vmiop   2     2Gi      33m …
```

Add GPU profile name related information to kubectl get vmclass command

---

api/v1alpha1/virtualmachineclass_types.go

We added support to print VGPU device/passthrough device-related information in PR
https://github.com/vmware-tanzu/vm-operator-api/pull/70. 
The PR did not unpack the individual array elements due to this bug, https://github.com/kubernetes/kubectl/issues/517
Since the upstream bug is getting traction, leverage wildcard `*` to unpack profileNames for VGPU devices
and device IDs for passthrough devices in kubectl get vmclass output 
```
root@42255e5e354ccbd32859ca7470f8897f [ ~ ]# kubectl get vmclass -o wide
NAME                            NAME   CPU   MEMORY   AGE     VGPUDEVICESPROFILENAMES   PASSTHROUGHDEVICEIDS
best-effort-2xlarge                    8     64Gi     7d1h
best-effort-4xlarge                    16    128Gi    7d1h
best-effort-8xlarge                    32    128Gi    7d1h …
```

Change kubectl get vmclass to print unpacked VGPU device and DDPIO devices data

---

api/v1alpha1/condition_consts.go
api/v1alpha1/virtualmachineimage_types.go

- This change adds the ovf Hardware Version to the VirtualMachineImage
object.
- It also deprecates some condition constants which won't be used

Add Virtual Hardware Version to the VirtualMachineImage Spec and some cleanup

---

api/v1alpha1/condition_consts.go

This introduces VSphereVMCustomization condition and reasons that expose the current status (weather it's running/pending/success/fail).
The status maps 1:1 with the recently released (7.0.2.0) vSphere GuestInfo API CustomizationInfo

Introduce VSphereVMCustomization condition and reasons

---

api/v1alpha1/condition_consts.go

This change renames the `VSphereVMCustomization` condition to be something that is more generic, leaving room for supporting additional (non vsphere/vmtools) based customizations in the future.

Rename Condition VSphereVMCustomization to GuestCustomization

---

api/v1alpha1/virtualmachine_types.go

This change introduces a const - VirtualMachineMetadataCloudInitPrepTransport = "CloudInitPrep" which will set the VirtualMachineMetadata ConfigMap data as cloud-init userdata.

Introduce CloudInitPrep type VirtualMachine Metadata transport

---

api/v1alpha1/condition_consts.go

This change adds condition types for the running status of
VMware tools, which will be exposed on the VirtualMachine CRD's status

Add Condition Types for VMTools running status

---

api/v1alpha1/virtualmachineclass_types.go

This PR Intoduces Instance Storage Volumes APIs as a peer of the Virtual Devices spec. The Instance Storage struct contains the specification required to configure instance storage for virtual machines. An admin can create VM classes with instance storage volumes and assign them to Supervisor namespaces for consumption. These VM classes can be used to create virtual machines that have instance storage volumes attached as disks. The generated instance volumes are placed on vSAN Direct datastores of the underlying host.

Introduce Instance Storage Volume APIs

---

api/v1alpha1/virtualmachinesetresourcepolicy_types.go

This field will contain the domain-XXX that corresponds to the
ClusterComputeResource. The VC Cluster Modules API is not very
friendly for our needs: the module create API does not take a
name or other identifier, so we're force to keep the module ID
in our status to be able to look it up. With future HA support,
we need create the modules on each cluster, so we also need the
cluster in the status.

Add Cluster to the ClusterModuleStatus

---

api/v1alpha1/virtualmachineclass_types.go

Otherwise existing classes are invalid:
... is invalid: spec.hardware.instanceStorage.volumes: Invalid value: \"null\":
spec.hardware.instanceStorage.volumes in body must be of type array: \"null\"",
Tweak field wording a bit.
This should use later use CRD validation to enforce a non-empty array.
The optional structs of the VirtualMachineClassHardware probably made/make
more sense as pointers.

Quick fix to make instanceStorage.volumes omitempty

---

api/v1alpha1/contentsourcebinding_types.go
api/v1alpha1/virtualmachineclassbinding_types.go

removing VirtualMachineClass column from ```kubectl get virtualmachineclassbindings```
removing ContentSource column from ```kubectl get contentsourcebindings```
```
root@421077164532703f248269ee76533985 [ ~ ]# kubectl get virtualmachineclassbindings -A
NAMESPACE   NAME               AGE
test-ns     guaranteed-small   2m33s
test-ns     test-class         3m
root@421077164532703f248269ee76533985 [ ~ ]# kubectl get contentsourcebindings -A
NAMESPACE           NAME                                   AGE
test-ns             a165e320-4793-4cee-b785-88c0beeaef1b   3m11s
testing-namespace   a165e320-4793-4cee-b785-88c0beeaef1b   46s
```
Co-authored-by: Shijia Hu <hshijia@vmware.com>

Remove `VirtualMachineClass` and `ContentSource` from the `kubectl get`

---

api/v1alpha1/virtualmachineclass_types.go

For [VMSVC-307](https://jira.eng.vmware.com/browse/VMSVC-307)
VI admins can provide a description of a VM class when they create them from the VC UI (or VAPI). However, that description is not propagated to the custom resource since the CRD doesn't support it. 
To expose description field on -o yaml/-o json, I added a new type VirtualMachineClassDescription and include it in VirtualMachineClass.

Add 'Description' field to VM Class CRD

---

api/v1alpha1/virtualmachine_types.go

This change adds a SecretName field to the VirtualMachineMetadata to
support Secrets as a mode of transport. This field and the existing
VirtualMachineMetadata.ConfigMapName are mutually exclusive.

Support Secrets as a VirtualMachineMetadata Transport Resource

---

api/v1alpha1/virtualmachine_types.go

This patch adds .status.zone to the VirtualMachine API in order to surface the zone where a VM has been scheduled in a zone-aware cluster.

Add VirtualMachine.Status.Zone

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha1/virtualmachineclass_types.go

In order to support VADP based backup/restore of VM Service VMs, we
need to pause the reconcile while the VM is recreated from backup on
the infrastructure. This change introduces a pause annotation to
achieve this. When set, VM operator will not reconcile this VM until
this annotation is removed.

Introduce annotation to pause a VM reconcile

---

api/v1alpha1/virtualmachine_types.go

When the no-network annotation exists, no default network will be applied to the VM.
Otherwise, vm-operator will add a default network to the VM based on the network provider.

Add a NoDefaultNic Annotation.

---

api/v1alpha1/virtualmachineimage_types.go

`ContentLibraryRef` under Status object should not be a require field. Change it to be optional.

Make ContentLibraryRef field optional

---

api/v1alpha1/condition_consts.go
api/v1alpha1/contentlibraryprovider_types.go
api/v1alpha1/virtualmachine_types.go
api/v1alpha1/virtualmachineclass_types.go
api/v1alpha1/virtualmachineimage_types.go
api/v1alpha1/virtualmachinepublishrequest_types.go

This PR introduces the following changes:
- Add an optional `ContentVersion` field in `VirtualMachineImageStatus`
- Add some constants related to `VirtualMachineImage` conditions
- Update `printcolumn` remarks by adding a dash in multi-word access all types to keep consistency

Update VirtualMachineImage related fields and separate multi-words with dash in print column
